### ISSUE TITLE
MySQL container not missing anymore?

### ISSUE THREAD

**Issue by oliv3r** [porelli/firefox-sync#4]
> For example, syncstorage-rs has a [docker release on docker-hub](https://hub.docker.com/r/mozilla/syncstorage-rs/) but it is targeted to work exclusively with Google Spanner which is what Mozilla uses to provide the service.

Is this still true? Upstream has 'mysql e2e tests' and they push mysql enabled containers now again?

**Comment by oliv3r** [comment]
Hmm, so the default arg for DATABASE_BACKEND is indeed 'spanner', but from some discussions I gather this may become a runtime thing in the future?

**Comment by porelli** [comment]
Can you link the discussion? I don't see the tag you mentioned
